name: nginx-httpe2ban
services:
  nginx:
    container_name: nginx-container-name
    volumes:
      - ./site-example:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./access.log:/var/log/nginx/access.log:rw
      - ./banned.conf:/etc/nginx/conf.d/banned.conf:ro
      # - ./nginx_main.conf:/etc/nginx/nginx.conf # If you are using log format as json, take a look at this file
    image: nginx:latest
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
      - TZ=America/Sao_Paulo #³
  nginx_httpe2ban:
    container_name: httpe2ban
    volumes:
      - ./access.log:/httpe2ban/access.log:ro
      - ./banned.conf:/httpe2ban/banned.conf:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    image: aleixolucas/nginx-httpe2ban
    environment:
      TZ: "America/Sao_Paulo"
      POLICY: >
        {
            "404": {"limit": 10, "window": 60},
            "403": {"limit": 5, "window": 60},
            "401": {"limit": 5, "window": 60}
        }
      LOG_LEVEL: "INFO"
      BLOCK_TTL: 120
      # NGINX_LOG_JSON_MAP: >
      #   {
      #     "ip_address":"remote_addr",
      #     "datetime":"time_local",
      #     "request":"request",
      #     "url":"http_referer",
      #     "http_version":"server_protocol",
      #     "status_code":"status",
      #     "user_agent":"http_user_agent"
      #   }
    depends_on:
        - nginx